#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    pot_mGoal,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  encOdo,         sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ime_driveR,     sensorNone)
#pragma config(Sensor, I2C_2,  ime_driveL,     sensorNone)
#pragma config(Motor,  port2,           claw,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           driveLY1,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           driveLY2,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           mgLiftL,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mgLiftR,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           driveRY1,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           driveRY2,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           arm,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
static int autonomousMode = 0;
static bool gyroReady = false;
#include "Vex_Competition_Includes_M.c"
#include "auton_library_8059.c"
#include "getlcdbuttons.c"

/************************************************************************************/
/************************************* Setting **************************************/
/************************************************************************************/
//Select the operating habits
#define HJM

#ifdef HJM
#define mainJoyY Ch3 //ch4
#define mainJoyX Ch1 //ch2
#define secondaryJoyY Ch4
#define secondaryJoyX Ch2
#endif
/************************************************************************************/
/************************************** Common **************************************/
/************************************************************************************/

/************************************************************************************/
/******************************** Automous ******************************************/
/************************************************************************************/
#define MAX_CHOICE  3
#define MAX_CHOICE_LCD  2
static int lcdTelemMode = 0;
bool mAutonBool = false;
int autonNumber = 0;

void pre_auton()
{
	bStopTasksBetweenModes = true;
	//gyroSetPort(sGYRO);
	//delay(1100);
	//gyroReady = false;
	//gyroCalibrate();
	//gyroReady = true;
}

#include "autons_raw_8059.c"
task autonomous(){
	resetAll();
	initPids();
	clearDebugStream();
	clearLCDLine(0);clearLCDLine(1);
	switch (autonomousMode){
	case 0:
		skills178();
		break;
	case 1:

		break;
	case 2:

		break;
	case 3:

		break;
	default:
		break;
	}
}
/************************************************************************************/
/******************************* User control ***************************************/
/************************************************************************************/
void LcdAutonomousSet( int value, bool select = false )
{
	if(select) autonomousMode = value;
	if(autonomousMode == value) mAutonBool = true;
	else mAutonBool = false;
}

task LcdAutonomousSelection()
{
	TControllerButtons  button;
	autonNumber = 0;
	bLCDBacklight = true;
	mAutonBool = false;
	LcdAutonomousSet(0);
	while( true ){
		button = getLcdButtons();
		if( ( button == kButtonLeft ) || ( button == kButtonRight ) ) {
			if( button == kButtonLeft )
				if( --autonNumber < 0 ) autonNumber = MAX_CHOICE;
			if( button == kButtonRight){
				++lcdTelemMode;
				if( lcdTelemMode > MAX_CHOICE_LCD ) lcdTelemMode = 0;
				clearLCDLine(0);
			}
			LcdAutonomousSet(autonNumber);
		}
		if( button == kButtonCenter)
			LcdAutonomousSet( autonNumber, true );
		delay(25);
	}
}

void FwLcdControl_user()
{
	clearLCDLine(0);
	char str0[32]; char str1[32];
	switch(lcdTelemMode)
	{
	case 0:
		sprintf( str0, "%d %d", getGyroGlobal(), getSensorPotMGoal());
		break;
	case 1:
		sprintf( str0, "O:%d ", -SensorValue[sENCO]);
		break;
	case 2:

		break;
	default:
		clearLCDLine(0); break;
	}
	sprintf( str1, "B(%d)%d %1.2f", mAutonBool, autonNumber, nImmediateBatteryLevel/1000.0 );
	displayLCDString(0, 0, str0);
	displayLCDString(1, 1, str1);
}

task usercontrol()
{
	resetAll();
	stopTask(MobileGoalControl);
	stopTask(ClawControl);
	stopTask(ArmControl);

	startTask(LcdAutonomousSelection);

	int threshold = 20;
	int mainX = 0,mainY = 0,secondaryX = 0,secondaryY = 0;
	bool cl = false, lastPressed = true, armRun = false;

	while(true)
	{
		FwLcdControl_user();
		if(abs(vexRT[mainJoyY]) >= threshold)	mainY = vexRT[mainJoyY];
		else	mainY = 0;
		if(abs(vexRT[mainJoyX]) >= threshold)	mainX = vexRT[mainJoyX];
		else	mainX = 0;
		if(abs(vexRT[secondaryJoyY]) >= threshold)	secondaryY = vexRT[secondaryJoyY];
		else	secondaryY = 0;
		if(abs(vexRT[secondaryJoyX]) >= threshold)	secondaryX = vexRT[secondaryJoyX];
		else	secondaryX = 0;
		if(abs(mainY) < abs(secondaryY)) mainY = secondaryY;
		if(abs(mainX) < 40) mainX /= 2;

		//pwrDriveRight((mainY - mainX)*0.7874);
		//pwrDriveLeft((-mainX - mainY)*0.7874);

		pwrDriveRight((-mainY - mainX)*0.7874);
		pwrDriveLeft((-mainX + mainY)*0.7874);

		if(vexRT[Btn5U]){ pwrClaw(-127); cl=true; armRun=false;  }
		else if(vexRT[Btn5D]){ pwrClaw(127); cl=false; armRun=false; }
		else{
			if(cl && !armRun) pwrClaw(-30);
			else if(!armRun) pwrClaw(0);
		}

		if(vexRT[Btn7U]){ pwrClaw(-127); pwrArm(127); lastPressed = false; armRun=true;  }
		else if(vexRT[Btn7D]){  /*pwrClaw(-30); pwrArm(-127); cl=true;*/ if(!lastPressed){armRun=true; lastPressed = true; autonArm(IN); }  }
		else{ if(!lastPressed) pwrArm(0); }

		if(vexRT[Btn6U]) setMGLiftMotor(127);
		else if(vexRT[Btn6D]) setMGLiftMotor(-127);
		else {
			if(getSensorPotMGoal()>_tick_mobilegoalout) setMGLiftMotor(15);
			else setMGLiftMotor(0);
		}



		delay(30);
	}
}
